# Generated by Django 2.1.1 on 2018-09-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='customer_id',
            field=models.CharField(max_length=73, unique=True),
        ),
    ]
