# Generated by Django 2.1.1 on 2018-09-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_orderindividual'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='https://i.kym-cdn.com/entries/icons/original/000/016/212/manning.png'),
            preserve_default=False,
        ),
    ]
