# Generated by Django 2.1.1 on 2018-09-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='order_range',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
