# Generated by Django 2.1.1 on 2018-09-22 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_order_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='order_range',
            new_name='order_range_km',
        ),
    ]
