# Generated by Django 2.1.1 on 2018-09-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180922_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercombineduser',
            name='is_complete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
