# Generated by Django 2.1.1 on 2018-09-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ordercombineduser_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercombineduser',
            name='percentage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
