# Generated by Django 2.1.1 on 2018-09-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_ordercombineduser_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='order_range_km',
            field=models.IntegerField(default=10),
        ),
    ]
