# Generated by Django 2.1.1 on 2018-09-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180922_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='10 West Virginia Blvd, West Viriginia City, Taipei, Taiwan', max_length=130),
            preserve_default=False,
        ),
    ]
