# Generated by Django 2.1.1 on 2018-09-23 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercombined',
            name='date',
            field=models.DateField(default=datetime.date(2018, 9, 23)),
            preserve_default=False,
        ),
    ]
